<?php 

/*
 * implementation of hook_menu();
 */

function netsound_cart_menu(){
	$items = array();
	
	$items['ting/object/%/huskeliste'] = array(
	 'title' => t('Tilføj til huskeliste'),
    'page callback' => 'netsound_cart_add',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
	);
	
	
	return $items;
}

function netsound_cart_add($tingid){
  global $user;
	
	if($user->uid != 0){
		
		module_load_include('client.inc', 'ting');		
		$tingObj = ting_get_object_by_id($tingid);
				
		if(is_a($tingObj,'TingClientObject')){
			$params = array(
        'tstamp' => time(),
        'uid' => $user->uid,
        'ting_object_id' => $tingObj->id,
      );
			drupal_write_record('netsound_cart',$params);
	    drupal_set_message(t('!book er nu tilføjet din huskeliste',array('!book' => l($tingObj->title,'ting/object/'.$tingObj->id))));
	    drupal_goto();	
		}		
	}
}

function netsound_cart_add_link($tingid){
	return l(t('Tilføj til huskeliste'),'ting/object/'.$tingid.'/huskeliste',array('query' => drupal_get_destination(),'attributes' => array('class' => 'addtocart')));
}



?>