<?php 

/*
 * implementation of hook_menu();
 */
function netsound_cart_menu(){
	$items = array();
	
	$items['ting/object/%/huskeliste'] = array(
	 'title' => t('Tilføj til huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2,'add'),
    'access arguments' => array('access content'),
	);
	$items['ting/object/%/huskeliste/fjern'] = array(
	 'title' => t('Fjern fra huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2,'rm'),
    'access arguments' => array('access content'),
	);
	
	return $items;
}

/*
 * page callback used in hook_menu();
 */
function netsound_cart_modify($tingid,$mode){
  global $user;
	
	if($user->uid != 0){
		module_load_include('client.inc', 'ting');		
		$tingObj = ting_get_object_by_id($tingid);
				
		if(is_a($tingObj,'TingClientObject')){
			$params = array(
        'tstamp' => time(),
        'uid' => $user->uid,
        'ting_object_id' => $tingObj->id,
      );
      switch($mode){
        case 'add':
          drupal_write_record('netsound_cart',$params);
    	    drupal_set_message(t('!book er nu tilføjet din huskeliste',array('!book' => l($tingObj->title,'ting/object/'.$tingObj->id))));
    	    break;
        case 'rm':
          unset($params['tstamp']);
          db_query('DELETE from {netsound_cart} WHERE uid = %s AND ting_object_id = "%s"',$user->uid,$tingObj->id);
    	    drupal_set_message(t('!book er nu fjernet fra din huskeliste',array('!book' => l($tingObj->title,'ting/object/'.$tingObj->id))));
          break;  
      }
	    drupal_goto();	
		}		
	}
}

/*
 * sadd to cart link
 */
function netsound_cart_add_link($tingid){
	return l(t('Tilføj til huskeliste'),'ting/object/'.$tingid.'/huskeliste',array('query' => drupal_get_destination(),'attributes' => array('class' => 'addtocart')));
}

/*
 * Implementation of hook_block();
 */
function netsound_cart_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('What\'s in my cart?');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta){
      case 0:
      	global $user;
      	$rows = array();
      	module_load_include('client.inc', 'ting');    
      	
      	
        $block['subject'] = t('Min huskeliste');
        $res = db_query('SELECT DISTINCT ting_object_id, uid FROM {netsound_cart} WHERE uid = %d',array('%d' => $user->uid));
        while($row = db_fetch_array($res)){
        	$rows[] = elib_displaybookNEW(ting_get_object_by_id($row['ting_object_id']),'','small_rm');
        }
        //var_dump($rows);
        
        
        
        $block['content'] = implode($rows);
        
        if($block['content'] == ''){
        	$block['content'] = t('Der er ingen bøger på din huskeliste');
        }
                
        break;
    }
  return $block;
  }
}




?>