<?php

/**
 * Implementation of hook_init.
 */
function ebog_preview_init() {
  if (!defined('EBOG_PREVIEW_PATH')) {
    define('EBOG_PREVIEW_PATH', drupal_get_path('module', 'ebog_preview'));
  }

  drupal_add_js(EBOG_PREVIEW_PATH . '/js/ebog_preview_scripts.js', 'file');
}

/**
 * Implementation of hook_menu.
 */
function ebog_preview_menu() {
  $menu = array();

  $menu['ting/object/%/sample/preview'] = array(
    'title' => 'Preview ting ebook',
    'description' => 'Provide an ebook preview using Monocle.',
    'page callback' => 'ebog_preview_preview',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Make a preview of a selected item.
 *
 * @param $ting_id
 *   Ting object id
 */
function ebog_preview_preview($ting_id) {
  $isbn = elib_get_isbn_from_object_id($ting_id);
  $ean = convertToEAN($isbn);

  $client = elib_client();
  $client->setLibrary(variable_get('elib_retailer_id', ''));

  $book = $client->getBook($ean);
  $response = array();

  // Book fetched correctly
  if ($book->status->code == 101) {
    $preview_link = (string)$book->data->teaser->link;

    $response = array('status' => 'dl', 'msg' => $preview_link);
  }
  else {
    $response = array('status' => 'err', 'msg' => t('Book not found.'));
  }

  echo json_encode($response);
  exit(0);
}
