<?php
// $Id: location.kz.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Kazakhstan

function location_province_list_kz() {
  return array('ALA' => "Almaty",
    'AST' => "Astana",
    'ALM' => "Almaty",
    'AKM' => "Aqmola",
    'AKT' => "Aqtobe",
    'ATY' => "Atyrau",
    'ZAP' => "Baty Qazaqstan",
    'MAN' => "Mangghystau",
    'YUZ' => "Ongtustik Qazaqstan",
    'PAV' => "Paylodar",
    'KAR' => "Qaraghandy",
    'KUS' => "Qustanay",
    'KZY' => "Qyzylorda",
    'VOS' => "Shyghys Qazaqstan ",
    'SEV' => "Soltustik Qazaqstan ",
    'ZHA' => "Zhambyl");
}
