<?php 

/*
 * Implementation of hook_menu();
 */
function reload_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Powered by RELOAD!');
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta){
      case 0:
        $block['subject'] = NULL;
        $block['content'] = t('powered by !reload',array('!reload' => l(t('RELOAD!','http://www.reload.dk'))));
        break;
    }
  return $block;
  }
}







?>