<?php 


function elib_block_lastloans_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
	  $blocks[0]['info'] = t('Last loans');
	  $blocks[1]['info'] = t('Newest books');
	  $blocks[2]['info'] = t('Popular books books');
	  $blocks[3]['info'] = t('Welcome block - my page');
	  $blocks[4]['info'] = t('dummyblock2 books');
	  $blocks[5]['info'] = t('Logout block button');
	  return $blocks;
  }
  elseif ($op == 'view') {
    //global $user;
    $block = array();
     
    
    elib_client()->setLibrary(variable_get('elib_retailer_id', ''));
    module_load_include('client.inc', 'ting');
    
    switch($delta){
    	case 0:
    		
		    $response = elib_client()->getLatestLoans();  
		    
		    
		    foreach($response as $isbn){
		      $out .= elib_displaybookNEW(ting_get_object_by_isbn($isbn),'','lorem'); 
		    }
		    $block['subject'] = t('Seneste anmeldelser');	
    		break;
    	case 1:
    		$response = elib_client()->getNewBooks();
    		
    		
    		//var_dump($response);
    		   		
    		
	    		foreach($response->data->toplistitem as $item){
	    			dsm($item->ebookid.'<br/>');
	    			//print $item['ebookid'].'--';
	    			if(ting_get_object_by_isbn(trim($item->ebookid))){
	    				$out .= elib_displaybookNEW(ting_get_object_by_isbn(trim($item->ebookid)),'','small');
	    			}
	    			if($out == ''){
	    				$out = t('Der er ingen nye bøger');
	    			}
	    		}
    		 
    		$block['subject'] = t('Nyeste bøger');
    		break;
    	case 2:
    		$out = 'popular books';
    		$block['subject'] = t('populære bøger');
    		break;
    	case 3:
       
    		$out = '<p>'.t('Velkommen! Som bruger på %library bibliotek kan du låne %amount om måneden').'</p>'; 
    		        //$block['subject'] = t('Populære bøger');  
        break;
    	case 5:
    		global $user;
    		$block['subject'] = t('Min profil');
    		if($user->uid){
    			$out = '<p>Du er logget ind: '.l('Log ud','logout',array('attributes' => array('class' => 'biglogoutbutton'))).'</p>';
    		}
    		break;
    }
    
    //krumo($books);
    
    //$response = elib_client()->getNewBooks();
    
 
    
      
      $block['content'] = $out;

    
    
    return $block;
  }
  
} 















?>