<?php 


function elib_block_lastloans_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
	  $blocks[0]['info'] = t('Last loans');
	  $blocks[1]['info'] = t('Newest books');
	  $blocks[2]['info'] = t('Popular books books');
	  $blocks[3]['info'] = t('dummyblock1 books');
	  $blocks[4]['info'] = t('dummyblock2 books');
	  $blocks[5]['info'] = t('Logout block button');
	  return $blocks;
  }
  elseif ($op == 'view') {
    //global $user;
    $block = array();
     
    
    elib_client()->setLibrary(variable_get('elib_retailer_id', ''));
    module_load_include('client.inc', 'ting');
    
    switch($delta){
    	case 0:
    		
		    $response = elib_client()->getLatestLoans();  
		    
		    
		    foreach($response as $isbn){
		      $out .= elib_displaybookNEW(ting_get_object_by_isbn($isbn),'','lorem'); 
		    }
		    $block['subject'] = t('Seneste anmeldelser');	
    		break;
    	case 1:
    		$response = elib_client()->getNewBooks();
    		
    		if(is_array($response->data->toplistitem)){
	    		foreach($response->data->toplistitem as $item){
	    			//var_dump($item->ebookid);
	    			//print $item['ebookid'].'--';
	    			if(ting_get_object_by_isbn(trim($item->ebookid))){
	    				$out .= elib_displaybookNEW(ting_get_object_by_isbn(trim($item->ebookid)),'','small');
	    			}
	    			if($out == ''){
	    				$out = t('Der er ingen nye bøger');
	    			}
	    		}
    		} 
    		$block['subject'] = t('Nyeste bøger');
    		break;
    	case 2:
    		$out = 'popular books';
    		$block['subject'] = t('populære bøger');
    		break;
    	case 3:
        
        $response = elib_client()->getLatestLoans();  
        
        shuffle($response);
        
        foreach($response as $isbn){
          $out .= elib_displaybookNEW(ting_get_object_by_isbn($isbn),'','small'); 
        }
        $block['subject'] = t('Populære bøger');  
        break;
    	case 5:
    		$block['subject'] = t('Min profil');
    		$out = '<p>Du er logget ind<p>'.l('logud','logout',array('attributes' => array('class' => 'biglogoutbutton')));
    		break;
    }
    
    //krumo($books);
    
    //$response = elib_client()->getNewBooks();
    
 
    
      
      $block['content'] = $out;

    
    
    return $block;
  }
  
} 















?>