<?php
/**
 * @file webtrends.module
 */

/**
 * Implementation of hook_menu()
 *
 * @return array $items
 */
function webtrends_menu() {
  $items = array();

  $items['admin/settings/webtrends'] = array(
    'title' => 'Webtrends',
    'description' => 'Configure the Webtrends tracking integration settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webtrends_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'webtrends_admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_init() to check roles and add the Webtrends javascript file
 *
 * @return null
 */
function webtrends_init() {
  global $user;
  global $webtrends_init;
  $webtrends_init = false;

  $webtrends_enabled_roles = explode('_', variable_get('webtrends_enabled_roles', ''));

  if (is_array($webtrends_enabled_roles) && count($webtrends_enabled_roles)) {

    $show_for_role = (bool) array_uintersect($webtrends_enabled_roles, array_keys($user->roles), "strcasecmp");

    if ($show_for_role) {
      $webtrends_init = true;
      drupal_add_js(drupal_get_path('module', 'webtrends').'/js/webtrends.js');
    }
  }
}

/**
 * Implementation of hook_footer() to insert Webtrends initialization script at the end of the page
 *
 * @return string $script
 */
function webtrends_footer() {
  $script = '';
  $webtrends_values = array();
  
  foreach (module_list() as $module) {
    $function = $module .'_wt_values';
    if (function_exists($function)) {
      $webtrends_values = $function();
    }
  }

  global $webtrends_init;

  if ($webtrends_init) {
    $script  = '<script type="text/javascript">'."\n";
    $script .= '//<![CDATA['."\n";
    $script .= 'var _tag=new WebTrends();'."\n";
    $script .= '_tag.dcsGetId();'."\n";
    $script .= '//]]>'."\n";
    $script .= '</script>'."\n";
    $script .= '<script type="text/javascript">'."\n";
    $script .= '//<![CDATA['."\n";
    $script .= '_tag.dcsCollect();'."\n";
    $script .= '//]]>'."\n";
    $script .= '</script>'."\n";
    $script .= '<noscript>'."\n";
    $script .= '<div>'."\n";
    $script .= '<img alt="DCSIMG" id="DCSIMG" width="1" height="1" src="https://visionize10.visionize.dk/dcspimbaa10000oqojwrx2td2_1c3r/njs.gif?dcsuri=/nojavascript&amp;WT.js=No&amp;WT.tv=9.4.0&amp;dcssip=www.ereolen.dk"/>'."\n";
    $script .= '</div>'."\n";
    $script .= '</noscript>'."\n";
  }
  
  return $script;
}
