<?php 

function elib_libraries_menu() {
  $items = array();
  
  //return;
  
  $items['admin/settings/elib/lib'] = array(
    'title'            => 'eLib settings',
    'description'      => 'settings for eLib SOAP webservice',
    'access arguments' => array('access administration pages'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ting_admin_settings_form_elib'),
    'file'             => 'elib_libraries.admin.inc',
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 2,
  );
  $items['getlibrary/%'] = array(
    'title' => 'getlib',
    'page callback' => 'elib_libraries_findlib',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  return $items;
}
function elib_libraries_findlib($cpr){
	$res = db_query('SELECT elib_library FROM {elib_user} WHERE elib_user.elib_id = "'.elib_user_elib_id($cpr).'"');
	print json_encode(db_fetch_array($res));
}

function elib_libraries_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      $form['library'] = array(
        '#type' => 'select',
        '#title' => t('Dit bibliotek'),
        //'#default_value' => variable_get('feed_item_length','teaser'),
          '#options' => 
            elib_libraries_get_libraries()
          
        #'#description' => t('Choose the library with which you\'re connected inorder to loan the audio book'),
      );
      break;
  }
}


function elib_libraries_get_libraries(){
	$matrix = variable_get('elib_libraries', '');
	if($matrix == ''){
		return false;
	}
	$libraries = explode("\n",$matrix);
	foreach ($libraries as $library){
		 $p = explode('|',$library);
		  $libs[trim($p[0])] = trim($p[1]);		//
	}
	
	return $libs;
}
function elib_libraries_get_library_keycode($lib){
  $matrix = variable_get('elib_libraries', '');
  if($matrix == ''){
    return false;
  }
  
  $libraries = explode("\n",$matrix);
  foreach ($libraries as $library){
    $p = explode('|',$library);
    if($p[0] == $lib){
     	return $p[2];
    }    
  }
}
function elib_libraries_get_maxloans($lib){
  $matrix = variable_get('elib_libraries', '');
  if($matrix == ''){
    return false;
  }
  $libraries = explode("\n",$matrix);
  foreach ($libraries as $library){
    $p = explode('|',$library);
    if($p[0] == $lib){
      return $p[3];
    }    
  }
	
}


?>